
function renderQuiz(quiz, mountId){
  const root=document.getElementById(mountId);
  root.classList.add('quiz');
  root.innerHTML = `<div class="card-box"><div class="counter" id="count"></div><div class="progress" aria-hidden="true"><div id="progbar"></div></div><div class="qtext" id="qtext" role="heading"></div><div id="choices" class="choices" role="listbox"></div><div class="feedback" id="feedback" aria-live="polite"></div><div class="controls"><a href="#" class="button" id="nextBtn">Next</a><a href="#" class="button" id="submitBtn" style="display:none">Submit</a></div></div><div class="card-box" id="resultCard" style="display:none"></div>`;
  const qtext=root.querySelector('#qtext'), choicesDiv=root.querySelector('#choices'), feedback=root.querySelector('#feedback'), nextBtn=root.querySelector('#nextBtn'), submitBtn=root.querySelector('#submitBtn'), prog=root.querySelector('#progbar'), count=root.querySelector('#count'), resultCard=root.querySelector('#resultCard');
  let idx=0, score=0, answered=false;
  function draw(){ const q=quiz[idx]; qtext.textContent=q.q; feedback.textContent=''; answered=false; choicesDiv.innerHTML=q.choices.map((c,i)=>'<div class="choice" tabindex="0" data-i="'+i+'"><div class="ix">'+(i+1)+'</div><div>'+c+'</div></div>').join(''); const first=choicesDiv.querySelector('.choice'); if(first) first.focus(); prog.style.width=Math.round(idx/quiz.length*100)+'%'; count.textContent='Question '+(idx+1)+' of '+quiz.length; nextBtn.style.display=(idx<quiz.length-1)?'inline-block':'none'; submitBtn.style.display=(idx===quiz.length-1)?'inline-block':'none'; }
  function answer(pick){ if(answered) return; const q=quiz[idx]; const nodes=choicesDiv.querySelectorAll('.choice'); nodes.forEach((n,i)=>{ if(i===q.a) n.classList.add('correct'); if(i===pick && pick!==q.a) n.classList.add('wrong'); }); if(pick===q.a){ score++; feedback.textContent='✅ Correct — '+q.e; } else { feedback.textContent='❌ Try again — '+q.e; } answered=true; (nextBtn.style.display==='none'?submitBtn:nextBtn).focus(); }
  choicesDiv.addEventListener('click', e=>{ const ch=e.target.closest('.choice'); if(!ch) return; answer(Number(ch.getAttribute('data-i'))); });
  choicesDiv.addEventListener('keydown', e=>{ const choices=Array.from(choicesDiv.querySelectorAll('.choice')); const iFocus=choices.indexOf(document.activeElement); const move=(d)=>{ const t=choices[Math.max(0,Math.min(choices.length-1,iFocus+d))]; if(t) t.focus(); }; if(['ArrowDown','ArrowRight'].includes(e.key)){ e.preventDefault(); move(1);} if(['ArrowUp','ArrowLeft'].includes(e.key)){ e.preventDefault(); move(-1);} if(['Enter',' '].includes(e.key)){ e.preventDefault(); const i=document.activeElement.getAttribute('data-i'); if(i!=null) answer(Number(i)); } if(['1','2','3','4'].includes(e.key)){ const n=Number(e.key)-1; if(n>=0) answer(n); } });
  nextBtn.addEventListener('click', e=>{ e.preventDefault(); if(!answered) return; idx++; draw(); });
  submitBtn.addEventListener('click', e=>{ e.preventDefault(); if(!answered) return; const pct=Math.round(score/quiz.length*100); resultCard.style.display='block'; resultCard.innerHTML='<h3>Your Score: '+pct+'%</h3><p>Correct: '+score+' / '+quiz.length+'</p><div class="controls"><a class="button" href="#" onclick="location.reload();return false;">Play Again</a><a class="button" href="../lessons.html" style="margin-left:8px">Back to Lessons</a></div>'; });
  draw();
}
